name: smart_food_app
description: Smart Online Food Ordering App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6


  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^13.0.0

  # UI
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0

  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  badges: ^3.1.2
  lottie: ^3.0.0

  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1


  # Payment
  url_launcher: ^6.2.2

  # Local Storage
  shared_preferences: ^2.2.2

  # Utils
  intl: ^0.19.0
  image_picker: ^1.0.7
  uuid: ^4.3.3
  equatable: ^2.0.5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
