// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6BCoNsGNUIcMGuBst7DqyiIcOteFE-Io',
    appId: '1:279504028526:web:921f35e4c7c1f204d7777f',
    messagingSenderId: '279504028526',
    projectId: 'my-food-app-294fd',
    authDomain: 'my-food-app-294fd.firebaseapp.com',
    storageBucket: 'my-food-app-294fd.firebasestorage.app',
    measurementId: 'G-DJS15354LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrLeYWn-ia3o1sGHlaNhI3x9FcMC2F8GI',
    appId: '1:279504028526:android:a8702e513b418f0ed7777f',
    messagingSenderId: '279504028526',
    projectId: 'my-food-app-294fd',
    storageBucket: 'my-food-app-294fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQLBkrJGY1GC86b7AKSoEpbk5tnsWQAQ',
    appId: '1:279504028526:ios:00b92bc095832bcad7777f',
    messagingSenderId: '279504028526',
    projectId: 'my-food-app-294fd',
    storageBucket: 'my-food-app-294fd.firebasestorage.app',
    iosBundleId: 'com.example.smartFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQLBkrJGY1GC86b7AKSoEpbk5tnsWQAQ',
    appId: '1:279504028526:ios:00b92bc095832bcad7777f',
    messagingSenderId: '279504028526',
    projectId: 'my-food-app-294fd',
    storageBucket: 'my-food-app-294fd.firebasestorage.app',
    iosBundleId: 'com.example.smartFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6BCoNsGNUIcMGuBst7DqyiIcOteFE-Io',
    appId: '1:279504028526:web:e0acb569a577d024d7777f',
    messagingSenderId: '279504028526',
    projectId: 'my-food-app-294fd',
    authDomain: 'my-food-app-294fd.firebaseapp.com',
    storageBucket: 'my-food-app-294fd.firebasestorage.app',
    measurementId: 'G-2B5PHMVR28',
  );

}