import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> seedFoodItems() async {
  final db = FirebaseFirestore.instance;
  final collection = db.collection('foodItems');

  final existing = await collection.limit(1).get();
  if (existing.docs.isNotEmpty) {
    print('✅ Food items already exist. Skipping.');
    return;
  }
  final restaurantsSnap = await db.collection('restaurants').get();
  final Map<String, String> restaurantIds = {};
  for (final doc in restaurantsSnap.docs) {
    restaurantIds[doc.data()['name']] = doc.id;
  }

  print('🌱 Found ${restaurantIds.length} restaurants. Seeding food items...');

  final List<Map<String, dynamic>> foodItems = [

    {
      'restaurantId': restaurantIds["Sultan's Dine"] ?? '',
      'name': 'Kacchi Biriyani (Half)',
      'description': 'Tender mutton with fragrant basmati rice cooked in authentic spices',
      'imageUrl': 'https://sultansdinebd.com/wp-content/uploads/2023/09/2-half-kacchi-450x450.jpg',
      'price': 280.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller', 'spicy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds["Sultan's Dine"] ?? '',
      'name': 'Kacchi Biriyani (Full)',
      'description': 'Full plate of tender mutton biriyani with raita and salad',
      'imageUrl': 'https://sultansdinebd.com/wp-content/uploads/2023/09/2-half-kacchi-450x450.jpg',
      'price': 480.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds["Sultan's Dine"] ?? '',
      'name': 'Beef Rezala',
      'description': 'Slow-cooked beef in creamy white gravy with aromatic Mughal spices',
      'imageUrl': 'https://images.unsplash.com/photo-1545247181-516773cae754?w=400',
      'price': 320.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': ['mughal'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds["Sultan's Dine"] ?? '',
      'name': 'Plain Rice',
      'description': 'Steamed basmati rice — perfect side dish',
      'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'price': 60.0,
      'category': 'Bangladeshi',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['side'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds["Sultan's Dine"] ?? '',
      'name': 'Borhani',
      'description': 'Traditional spiced yogurt drink — perfect with biriyani',
      'imageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8bN_1tBOQqegtTCHvVpcLtmvBQSAtqRk-hw&s',
      'price': 60.0,
      'category': 'Bangladeshi',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['drink'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Chillox'] ?? '',
      'name': 'Classic Smash Burger',
      'description': 'Double smashed beef patty with cheese, lettuce and special sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      'price': 350.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller', 'spicy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Chillox'] ?? '',
      'name': 'Chicken Crispy Burger',
      'description': 'Crispy fried chicken with coleslaw and honey mustard',
      'imageUrl': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400',
      'price': 280.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['crispy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Chillox'] ?? '',
      'name': 'Loaded Fries',
      'description': 'Crispy fries loaded with cheese sauce and jalapenos',
      'imageUrl': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
      'price': 180.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['snack'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Chillox'] ?? '',
      'name': 'Beef Meatbox',
      'description': 'Beef patty, fries, coleslaw and soft drink combo',
      'imageUrl': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
      'price': 480.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['combo', 'bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Kacchi Vai'] ?? '',
      'name': 'Special Kacchi (Half)',
      'description': 'Signature mutton kacchi with egg and potato',
      'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'price': 250.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Kacchi Vai'] ?? '',
      'name': 'Special Kacchi (Full)',
      'description': 'Full plate signature kacchi biriyani with raita',
      'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'price': 450.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Kacchi Vai'] ?? '',
      'name': 'Chicken Biriyani',
      'description': 'Tender chicken with fragrant basmati rice',
      'imageUrl': 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400',
      'price': 180.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': [],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Kacchi Vai'] ?? '',
      'name': 'Firni',
      'description': 'Traditional sweet rice pudding dessert — a Bengali classic',
      'imageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgIgXSlxc4Te0thLqzerllLyI1svOXpFTbSw&s',
      'price': 80.0,
      'category': 'Dessert',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['dessert', 'sweet'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds["Domino's Pizza"] ?? '',
      'name': 'Pepperoni Pizza (Regular)',
      'description': 'Classic pepperoni with mozzarella on tomato base',
      'imageUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
      'price': 450.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds["Domino's Pizza"] ?? '',
      'name': 'Margherita Pizza (Regular)',
      'description': 'Fresh tomato, mozzarella and basil on thin crust',
      'imageUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      'price': 380.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['veg'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds["Domino's Pizza"] ?? '',
      'name': 'BBQ Chicken Pizza (Large)',
      'description': 'Smoky BBQ sauce with grilled chicken and caramelized onions',
      'imageUrl': 'https://images.unsplash.com/photo-1555072956-7758afb20e8f?w=400',
      'price': 680.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller', 'large'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds["Domino's Pizza"] ?? '',
      'name': 'Garlic Bread',
      'description': 'Freshly toasted bread with garlic butter, herbs and cheese dip',
      'imageUrl': 'https://cdn.jwplayer.com/v2/media/MvCHkL6u/poster.jpg?width=1280',
      'price': 150.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['snack', 'side'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['PizzaBurg'] ?? '',
      'name': 'PizzaBurg Special Pizza',
      'description': 'Signature pizza with special toppings — our bestseller!',
      'imageUrl': 'https://www.bdgift.com/pp/homepage/send_pizza_burg_pizza_to_Bangladesh.jpg',
      'price': 520.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['signature', 'bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['PizzaBurg'] ?? '',
      'name': 'Double Decker Burger',
      'description': 'Two juicy beef patties with special house sauce and fresh veggies',
      'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      'price': 380.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['PizzaBurg'] ?? '',
      'name': 'Cheese Fries',
      'description': 'Golden crispy fries with melted cheese sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
      'price': 160.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['side'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Fuoco'] ?? '',
      'name': 'Wood-fired Margherita',
      'description': 'Classic Italian pizza baked in authentic wood-fired oven',
      'imageUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      'price': 580.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': true,
      'tags': ['veg', 'italian'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Fuoco'] ?? '',
      'name': 'Spaghetti Carbonara',
      'description': 'Creamy pasta with crispy bacon, egg and freshly grated parmesan',
      'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
      'price': 480.0,
      'category': 'Pasta',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['italian', 'bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Fuoco'] ?? '',
      'name': 'Penne Arrabiata',
      'description': 'Spicy tomato sauce with penne pasta and fresh herbs',
      'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
      'price': 380.0,
      'category': 'Pasta',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['veg', 'spicy'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Khanas'] ?? '',
      'name': 'Dal Bhaat',
      'description': 'Homestyle lentil soup with steamed rice and pickle',
      'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'price': 120.0,
      'category': 'Bangladeshi',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': true,
      'tags': ['homestyle', 'healthy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Khanas'] ?? '',
      'name': 'Chicken Curry with Rice',
      'description': 'Traditional Bangladeshi chicken curry with steamed rice',
      'imageUrl': 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      'price': 180.0,
      'category': 'Bangladeshi',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['homestyle'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Khanas'] ?? '',
      'name': 'Fish Curry',
      'description': 'Fresh Hilsha fish cooked in traditional Bangladeshi mustard spices',
      'imageUrl': 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400',
      'price': 200.0,
      'category': 'Bangladeshi',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': ['fish'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Khanas'] ?? '',
      'name': 'Cold Coffee',
      'description': 'Refreshing chilled coffee with milk and ice cream — a perfect treat',
      'imageUrl': 'https://www.milkmaid.in/sites/default/files/2024-05/Cold-Coffee-335x300.jpg',
      'price': 120.0,
      'category': 'Bangladeshi',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['drink', 'cold'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['ChaapGhor'] ?? '',
      'name': 'Beef Chaap',
      'description': 'Slow-cooked spicy beef ribs — Old Dhaka\'s most famous dish',
      'imageUrl': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
      'price': 220.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['spicy', 'bestseller', 'old-dhaka'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['ChaapGhor'] ?? '',
      'name': 'Beef Kabab (6 pcs)',
      'description': 'Juicy minced beef kababs on skewers with chutney',
      'imageUrl': 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400',
      'price': 180.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['grilled'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['ChaapGhor'] ?? '',
      'name': 'Naan Bread',
      'description': 'Freshly baked soft naan from traditional tandoor oven',
      'imageUrl': 'https://thestayathomechef.com/wp-content/uploads/2020/05/Homemade-Naan-Bread-1.jpg',
      'price': 40.0,
      'category': 'Bangladeshi',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['bread', 'side'],
      'createdAt': FieldValue.serverTimestamp(),
    },


    {
      'restaurantId': restaurantIds['Sweet Cravings'] ?? '',
      'name': 'Chocolate Truffle Cake',
      'description': 'Rich dark chocolate cake with silky truffle frosting — indulge yourself',
      'imageUrl': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
      'price': 450.0,
      'category': 'Cakes',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': true,
      'tags': ['bestseller', 'chocolate'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Sweet Cravings'] ?? '',
      'name': 'Red Velvet Cake',
      'description': 'Classic red velvet with smooth cream cheese frosting',
      'imageUrl': 'https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=400',
      'price': 480.0,
      'category': 'Cakes',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': true,
      'tags': ['popular'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Sweet Cravings'] ?? '',
      'name': 'Gulab Jamun (6 pcs)',
      'description': 'Soft milk-solid balls soaked in rose-flavored sugar syrup — a classic dessert',
      'imageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRHpjmf-6lWzOzxaL_kZBfJtknukk1ZnnK_g&s',
      'price': 120.0,
      'category': 'Dessert',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['sweet', 'traditional'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['KFC'] ?? '',
      'name': 'Original Recipe Chicken (2 pcs)',
      'description': 'Iconic crispy fried chicken with 11 secret herbs and spices',
      'imageUrl': 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
      'price': 320.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller', 'crispy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['KFC'] ?? '',
      'name': 'Zinger Burger',
      'description': 'Spicy crispy chicken fillet burger with tangy mayo',
      'imageUrl': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400',
      'price': 280.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['spicy', 'bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['KFC'] ?? '',
      'name': 'Bucket Meal (8 pcs)',
      'description': '8 pieces of original recipe chicken — perfect for sharing',
      'imageUrl': 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
      'price': 980.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['family', 'combo'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Burger King'] ?? '',
      'name': 'Whopper',
      'description': 'Flame-grilled beef with fresh vegetables, tomatoes and mayo',
      'imageUrl': 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=400',
      'price': 380.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller', 'flame-grilled'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Burger King'] ?? '',
      'name': 'Double Whopper',
      'description': 'Double flame-grilled beef patty — for the real burger lover',
      'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      'price': 520.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['double', 'premium'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Burger King'] ?? '',
      'name': 'Onion Rings',
      'description': 'Crispy golden battered onion rings with dipping sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
      'price': 150.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['side', 'crispy'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Kacchi Darbar'] ?? '',
      'name': 'Special Kacchi (Half)',
      'description': 'Signature mutton kacchi with egg, potato and raita',
      'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'price': 260.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Kacchi Darbar'] ?? '',
      'name': 'Special Kacchi (Full)',
      'description': 'Full plate signature kacchi biriyani with raita and salad',
      'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'price': 480.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Kacchi Darbar'] ?? '',
      'name': 'Chicken Biriyani',
      'description': 'Tender chicken pieces with fragrant basmati rice',
      'imageUrl': 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400',
      'price': 190.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': [],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Kacchi Darbar'] ?? '',
      'name': 'Firni',
      'description': 'Traditional sweet rice pudding — a Bengali classic dessert',
      'imageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgIgXSlxc4Te0thLqzerllLyI1svOXpFTbSw&s',
      'price': 80.0,
      'category': 'Dessert',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['dessert', 'sweet'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Cafe Darbar'] ?? '',
      'name': 'Cafe Special Set Menu',
      'description': 'Complete meal — biriyani + curry + raita + dessert + drink',
      'imageUrl': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
      'price': 550.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['combo', 'bestseller', 'set-menu'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Cafe Darbar'] ?? '',
      'name': 'Chicken Biriyani',
      'description': 'Aromatic chicken biriyani with saffron rice and raita',
      'imageUrl': 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400',
      'price': 220.0,
      'category': 'Biriyani',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['popular'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Cafe Darbar'] ?? '',
      'name': 'Beef Pasta',
      'description': 'Creamy pasta with tender beef chunks and special herbs',
      'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
      'price': 320.0,
      'category': 'Pasta',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': ['fusion'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Cafe Darbar'] ?? '',
      'name': 'Chicken Burger',
      'description': 'Grilled chicken fillet with lettuce, tomato and special sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400',
      'price': 250.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': [],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Cafe Darbar'] ?? '',
      'name': 'French Fries',
      'description': 'Crispy golden french fries seasoned with special spices',
      'imageUrl': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
      'price': 130.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['side', 'snack'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Crush Station'] ?? '',
      'name': 'Crush Special Set Menu',
      'description': 'Complete meal — burger + fries + shake combo',
      'imageUrl': 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=400',
      'price': 520.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['combo', 'bestseller', 'set-menu'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Crush Station'] ?? '',
      'name': 'Smash Beef Burger',
      'description': 'Smashed beef patty with cheese, pickles and special crush sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      'price': 360.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Crush Station'] ?? '',
      'name': 'Chicken Burger',
      'description': 'Crispy chicken fillet with coleslaw and honey mustard',
      'imageUrl': 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400',
      'price': 280.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': [],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Crush Station'] ?? '',
      'name': 'Beef Pasta',
      'description': 'Creamy beef pasta with herbs and parmesan',
      'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
      'price': 300.0,
      'category': 'Pasta',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': [],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Crush Station'] ?? '',
      'name': 'French Fries',
      'description': 'Crispy seasoned fries with ketchup and mayo',
      'imageUrl': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
      'price': 130.0,
      'category': 'Burger',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['side'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Crush Station'] ?? '',
      'name': 'Chocolate Shake',
      'description': 'Thick creamy chocolate milkshake with whipped cream',
      'imageUrl': 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=400',
      'price': 180.0,
      'category': 'Dessert',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['drink', 'sweet'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['Golden Pizza'] ?? '',
      'name': 'Cheese Pizza',
      'description': 'Classic golden crust loaded with extra mozzarella and cheddar cheese',
      'imageUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      'price': 420.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': true,
      'tags': ['cheesy', 'bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Golden Pizza'] ?? '',
      'name': 'BBQ Pizza',
      'description': 'Smoky BBQ sauce base with chicken, onions and bell peppers',
      'imageUrl': 'https://images.unsplash.com/photo-1555072956-7758afb20e8f?w=400',
      'price': 480.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bbq', 'spicy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Golden Pizza'] ?? '',
      'name': 'Golden Special Pizza',
      'description': 'Our signature pizza — beef, chicken, vegetables with special golden sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
      'price': 580.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['signature', 'special'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Golden Pizza'] ?? '',
      'name': 'Pepperoni Pizza',
      'description': 'Classic crispy pepperoni with mozzarella on tomato base',
      'imageUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
      'price': 460.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': ['popular'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Golden Pizza'] ?? '',
      'name': 'Veggie Pizza',
      'description': 'Fresh vegetables — capsicum, mushroom, olive, onion on thin crust',
      'imageUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      'price': 380.0,
      'category': 'Pizza',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['veg', 'healthy'],
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'restaurantId': restaurantIds['MasterChef'] ?? '',
      'name': 'Chef\'s Set Menu',
      'description': 'Complete continental meal — soup + main course + dessert + drink',
      'imageUrl': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
      'price': 850.0,
      'category': 'Rice',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['set-menu', 'premium', 'bestseller'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['MasterChef'] ?? '',
      'name': 'Beef Steak',
      'description': 'Juicy 200g beef tenderloin steak with mushroom sauce, mashed potato and grilled vegetables',
      'imageUrl': 'https://images.unsplash.com/photo-1546964124-0cce460f38ef?w=400',
      'price': 980.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['premium', 'continental'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['MasterChef'] ?? '',
      'name': 'Chicken Steak',
      'description': 'Grilled chicken breast with black pepper sauce, fries and coleslaw',
      'imageUrl': 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400',
      'price': 650.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['continental', 'grilled'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['MasterChef'] ?? '',
      'name': 'Prawn Fries',
      'description': 'Crispy battered tiger prawns with tartar sauce and lemon wedge',
      'imageUrl': 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400',
      'price': 750.0,
      'category': 'Meatbox',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': ['seafood', 'crispy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['MasterChef'] ?? '',
      'name': 'Pasta Alfredo',
      'description': 'Creamy white sauce pasta with mushroom and parmesan',
      'imageUrl': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
      'price': 420.0,
      'category': 'Pasta',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['italian', 'creamy'],
      'createdAt': FieldValue.serverTimestamp(),
    },


    {
      'restaurantId': restaurantIds['Rice Bowl'] ?? '',
      'name': 'Sausage Rice',
      'description': 'Fried rice with juicy sausage slices, egg and vegetables',
      'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'price': 180.0,
      'category': 'Rice',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['bestseller', 'fried-rice'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Rice Bowl'] ?? '',
      'name': 'Egg Fried Rice',
      'description': 'Classic fried rice with scrambled egg, soy sauce and spring onion',
      'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'price': 150.0,
      'category': 'Rice',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': true,
      'tags': ['popular', 'quick'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Rice Bowl'] ?? '',
      'name': 'Chicken Rice Bowl',
      'description': 'Grilled chicken with steamed jasmine rice, salad and special sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400',
      'price': 220.0,
      'category': 'Rice',
      'isAvailable': true,
      'isPopular': true,
      'isVeg': false,
      'tags': ['healthy', 'grilled'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Rice Bowl'] ?? '',
      'name': 'Vegetables Rice Bowl',
      'description': 'Healthy stir-fried seasonal vegetables with steamed rice and teriyaki sauce',
      'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'price': 160.0,
      'category': 'Rice',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': true,
      'tags': ['veg', 'healthy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'restaurantId': restaurantIds['Rice Bowl'] ?? '',
      'name': 'Beef Fried Rice',
      'description': 'Wok-tossed fried rice with tender beef strips and Asian spices',
      'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'price': 240.0,
      'category': 'Rice',
      'isAvailable': true,
      'isPopular': false,
      'isVeg': false,
      'tags': ['spicy'],
      'createdAt': FieldValue.serverTimestamp(),
    },
  ];

  int count = 0;
  int skipped = 0;
  for (final item in foodItems) {
    if ((item['restaurantId'] as String).isNotEmpty) {
      await collection.add(item);
      count++;
      print('✅ (${count}) ${item['name']}');
    } else {
      skipped++;
      print('⚠️ Skipped: ${item['name']} (restaurant not found)');
    }
  }

  print('🎉 Done! $count food items added. $skipped skipped.');
}