import 'package:cloud_firestore/cloud_firestore.dart';
Future<void> seedRestaurants() async {
  final db = FirebaseFirestore.instance;
  final collection = db.collection('restaurants');

  final existing = await collection.limit(1).get();
  if (existing.docs.isNotEmpty) {
    print('✅ Restaurants already exist. Skipping seed.');
    return;
  }
  print('🌱 Seeding restaurants...');
  final List<Map<String, dynamic>> restaurants = [

    {
      'name': "Sultan's Dine",
      'description': 'Authentic Bangladeshi & Mughal cuisine with rich flavors',
      'imageUrl': 'https://sultansdinebd.com/wp-content/uploads/2023/09/2-half-kacchi-450x450.jpg',
      'coverImageUrl': 'https://sultansdinebd.com/wp-content/uploads/2023/09/2-half-kacchi-450x450.jpg',
      'address': 'Gulshan-2, Dhaka',
      'latitude': 23.7936,
      'longitude': 90.4043,
      'categories': ['Biriyani', 'Bangladeshi', 'Meatbox'],
      'rating': 4.8,
      'totalRatings': 1250,
      'deliveryTime': 30,
      'deliveryFee': 30.0,
      'minimumOrder': 150.0,
      'openingTime': '10:00',
      'closingTime': '23:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner1',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Chillox',
      'description': 'Juicy burgers and crispy fries — comfort food at its best',
      'imageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      'address': 'Banani, Dhaka',
      'latitude': 23.7937,
      'longitude': 90.4066,
      'categories': ['Burger', 'Meatbox'],
      'rating': 4.7,
      'totalRatings': 980,
      'deliveryTime': 25,
      'deliveryFee': 25.0,
      'minimumOrder': 200.0,
      'openingTime': '11:00',
      'closingTime': '23:30',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner2',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Kacchi Vai',
      'description': 'Famous for authentic Kacchi Biriyani since 1985',
      'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'address': 'Mirpur, Dhaka',
      'latitude': 23.8041,
      'longitude': 90.3664,
      'categories': ['Biriyani', 'Bangladeshi'],
      'rating': 4.9,
      'totalRatings': 2100,
      'deliveryTime': 35,
      'deliveryFee': 20.0,
      'minimumOrder': 150.0,
      'openingTime': '12:00',
      'closingTime': '22:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner3',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': "Domino's Pizza",
      'description': 'Hot fresh pizza delivered to your door',
      'imageUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
      'address': 'Dhanmondi, Dhaka',
      'latitude': 23.7461,
      'longitude': 90.3742,
      'categories': ['Pizza'],
      'rating': 4.5,
      'totalRatings': 876,
      'deliveryTime': 30,
      'deliveryFee': 35.0,
      'minimumOrder': 250.0,
      'openingTime': '11:00',
      'closingTime': '23:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner4',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Fuoco',
      'description': 'Italian wood-fired pizza and pasta',
      'imageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLSiMlB5NdQS7K3E0RYxWyBSPEjiz53gldZA&s',
      'coverImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLSiMlB5NdQS7K3E0RYxWyBSPEjiz53gldZA&s',
      'address': 'Gulshan, Dhaka',
      'latitude': 23.7925,
      'longitude': 90.4078,
      'categories': ['Pizza', 'Pasta'],
      'rating': 4.6,
      'totalRatings': 654,
      'deliveryTime': 40,
      'deliveryFee': 40.0,
      'minimumOrder': 300.0,
      'openingTime': '12:00',
      'closingTime': '23:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner5',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Khanas',
      'description': 'Traditional Bangladeshi home-cooked meals',
      'imageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfQ0gol6IWCrDCW-RlwuSP73_PjZ-cpM5Gtg&s',
      'coverImageUrl': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfQ0gol6IWCrDCW-RlwuSP73_PjZ-cpM5Gtg&s',
      'address': 'Mohammadpur, Dhaka',
      'latitude': 23.7612,
      'longitude': 90.3578,
      'categories': ['Bangladeshi', 'Rice'],
      'rating': 4.4,
      'totalRatings': 432,
      'deliveryTime': 35,
      'deliveryFee': 20.0,
      'minimumOrder': 120.0,
      'openingTime': '08:00',
      'closingTime': '22:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner6',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'PizzaBurg',
      'description': 'Best of both worlds — pizza and burgers',
      'imageUrl': 'https://www.bdgift.com/pp/homepage/send_pizza_burg_pizza_to_Bangladesh.jpg',
      'coverImageUrl': 'https://www.bdgift.com/pp/homepage/send_pizza_burg_pizza_to_Bangladesh.jpg',
      'address': 'Uttara, Dhaka',
      'latitude': 23.8759,
      'longitude': 90.3795,
      'categories': ['Pizza', 'Burger'],
      'rating': 4.3,
      'totalRatings': 543,
      'deliveryTime': 30,
      'deliveryFee': 30.0,
      'minimumOrder': 200.0,
      'openingTime': '11:00',
      'closingTime': '23:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner7',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'ChaapGhor',
      'description': 'Spicy beef chaap and kababs Dhaka style',
      'imageUrl': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400',
      'address': 'Old Dhaka',
      'latitude': 23.7104,
      'longitude': 90.4074,
      'categories': ['Meatbox', 'Bangladeshi'],
      'rating': 4.7,
      'totalRatings': 1876,
      'deliveryTime': 45,
      'deliveryFee': 25.0,
      'minimumOrder': 150.0,
      'openingTime': '10:00',
      'closingTime': '00:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': true,
      'ownerId': 'owner8',
      'createdAt': FieldValue.serverTimestamp(),
    },

    {
      'name': 'MasterChef',
      'description': 'Continental and Asian fusion cuisine',
      'imageUrl': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
      'address': 'Baridhara, Dhaka',
      'latitude': 23.8019,
      'longitude': 90.4234,
      'categories': ['Rice', 'Pasta', 'Bangladeshi'],
      'rating': 4.2,
      'totalRatings': 321,
      'deliveryTime': 35,
      'deliveryFee': 35.0,
      'minimumOrder': 200.0,
      'openingTime': '11:00',
      'closingTime': '22:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner9',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Cafe Darbar',
      'description': 'Premium Indian and Bangladeshi cuisine',
      'imageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
      'address': 'Panthapath, Dhaka',
      'latitude': 23.7514,
      'longitude': 90.3944,
      'categories': ['Biriyani', 'Bangladeshi', 'Rice'],
      'rating': 4.5,
      'totalRatings': 765,
      'deliveryTime': 30,
      'deliveryFee': 30.0,
      'minimumOrder': 180.0,
      'openingTime': '10:00',
      'closingTime': '23:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner10',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Crush Station',
      'description': 'Trendy burgers, shakes and loaded fries',
      'imageUrl': 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1550317138-10000687a72b?w=400',
      'address': 'Bashundhara, Dhaka',
      'latitude': 23.8134,
      'longitude': 90.4241,
      'categories': ['Burger', 'Dessert'],
      'rating': 4.4,
      'totalRatings': 456,
      'deliveryTime': 25,
      'deliveryFee': 30.0,
      'minimumOrder': 200.0,
      'openingTime': '12:00',
      'closingTime': '23:30',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner11',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Kacchi Darbar',
      'description': 'Royal Kacchi Biriyani with secret spice blend',
      'imageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400',
      'address': 'Motijheel, Dhaka',
      'latitude': 23.7339,
      'longitude': 90.4184,
      'categories': ['Biriyani', 'Bangladeshi'],
      'rating': 4.6,
      'totalRatings': 987,
      'deliveryTime': 40,
      'deliveryFee': 20.0,
      'minimumOrder': 150.0,
      'openingTime': '11:00',
      'closingTime': '22:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner12',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Golden Pizza',
      'description': 'Golden crispy crust pizza with premium toppings',
      'imageUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
      'address': 'Shyamoli, Dhaka',
      'latitude': 23.7712,
      'longitude': 90.3612,
      'categories': ['Pizza'],
      'rating': 4.3,
      'totalRatings': 234,
      'deliveryTime': 30,
      'deliveryFee': 30.0,
      'minimumOrder': 200.0,
      'openingTime': '11:00',
      'closingTime': '23:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner13',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Sweet Cravings',
      'description': 'Cakes, desserts and sweet treats for every occasion',
      'imageUrl': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
      'address': 'Dhanmondi, Dhaka',
      'latitude': 23.7465,
      'longitude': 90.3768,
      'categories': ['Cakes', 'Dessert'],
      'rating': 4.6,
      'totalRatings': 543,
      'deliveryTime': 45,
      'deliveryFee': 40.0,
      'minimumOrder': 300.0,
      'openingTime': '10:00',
      'closingTime': '22:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner14',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Burger King',
      'description': 'Home of the Whopper — flame-grilled burgers',
      'imageUrl': 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=400',
      'address': 'Bashundhara City, Dhaka',
      'latitude': 23.7507,
      'longitude': 90.3932,
      'categories': ['Burger'],
      'rating': 4.4,
      'totalRatings': 1120,
      'deliveryTime': 30,
      'deliveryFee': 35.0,
      'minimumOrder': 250.0,
      'openingTime': '10:00',
      'closingTime': '23:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner15',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'KFC',
      'description': 'Finger lickin good fried chicken',
      'imageUrl': 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
      'address': 'Gulshan, Dhaka',
      'latitude': 23.7808,
      'longitude': 90.4093,
      'categories': ['Meatbox', 'Burger'],
      'rating': 4.3,
      'totalRatings': 1543,
      'deliveryTime': 25,
      'deliveryFee': 30.0,
      'minimumOrder': 200.0,
      'openingTime': '10:00',
      'closingTime': '23:30',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner16',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'name': 'Rice Bowl',
      'description': 'Healthy rice bowls and Asian cuisine',
      'imageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'coverImageUrl': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400',
      'address': 'Dhanmondi, Dhaka',
      'latitude': 23.7432,
      'longitude': 90.3712,
      'categories': ['Rice', 'Bangladeshi'],
      'rating': 4.1,
      'totalRatings': 187,
      'deliveryTime': 25,
      'deliveryFee': 20.0,
      'minimumOrder': 100.0,
      'openingTime': '09:00',
      'closingTime': '21:00',
      'isOpen': true,
      'isApproved': true,
      'isFeatured': false,
      'ownerId': 'owner17',
      'createdAt': FieldValue.serverTimestamp(),
    },
  ];
  for (int i = 0; i < restaurants.length; i++) {
    await collection.add(restaurants[i]);
    print('✅ (${i + 1}/${restaurants.length}) ${restaurants[i]['name']}');
  }

  print('🎉 Done! ${restaurants.length} restaurants added.');
}